#!/usr/bin/env ruby

require 'yaml'
require 'pathname'
class Pathname ; alias / + ; end

require 'thor'
require 'chronic'


$HERE = Pathname.new(__dir__)
$THEIR = Pathname.new(".")

module Helpers

  def parse_date(str)
    Chronic.parse(str.gsub(/[.]/, ' ')) unless str.to_s.empty?
  end
  def parse_date_with_name(str)
    date = parse_date(date)
    if date
      [date, nil]
    else
      [nil, str]
    end
  end
  def glob(str)
    s0 = str
    s1 = s0.gsub(/[.]/, '\.')
    s2 = s1.gsub(/[*]/, '.*')
    Regexp.new(s2, 'i')
  end
  def run_cmd(cmd)
    puts "$ #{cmd}" if $VERBOSE
    system cmd unless $DEBUG
  end
  def die(str)
    warn str
    exit 1
  end
  def open_file(file)
    run_cmd "open #{file}"
  end
  def remove_file(file)
    file.unlink
  end
  def create_file(file, content=nil)
    file.open("w") { |f|
      f << content if content
    }
  end
  def create_and_open_file(file, content=nil)
    create_file file, content
    open_file file
  end
  def open_or_create_file(file, content=nil)
    create_file file, content unless file.exist?
    open_file file
  end

end

module Orga

  module Conf
    class << self
      def points_dir() Pathname.new("_Points") end
      def clients_dir() Pathname.new(".") end
      def file_suffix() ".ft" end
      def file_suffix_ptn() Regexp.escape(file_suffix) end
    end
  end

  class Point < Thor
    include Helpers

    no_commands {
      def filter(filter)
        date, name = filter && parse_date_with_name(filter)
        Conf.points_dir.entries.map {|point|
          point_name = point.basename.to_path
          if point_name =~ /^(\d{4})-(\d{2})-(\d{2})-(.*)#{Conf.file_suffix_ptn}$/
            point_date = Time.new($1.to_i, $2.to_i, $3.to_i)
            if date && point_date < date
            elsif name && point_name !~ glob(name)
            else
              [date, point]
            end
          end
        }.compact.sort_by{|(d, e)| d }.map{|(d, e)| e }
      end
    }

    desc "add <name> <presents>", "Adds a point"
    def add(name, presents)
      presents = presents.split(",").map{|t| "@#{t.upcase}" }.sort

      date = Time.now.strftime("%Y-%m-%d")
      filename = "%s-%s.ft" % [date, name]
      file = Conf.points_dir + filename

      create_and_open_file file, <<CONTENT
\# #{date} — #{name} — #{presents.join(" - ")}

CONTENT
    end

    desc "open <ref>", "Open a point"
    def open(ref)
      files = filter(ref)
      case files.length
      when 0
        die "No file found for pattern '#{ref}'"
      when 1
        open_file(Conf.points_dir / files.first)
      else
        die "Too many files found for pattern '#{ref}'"
      end
    end

    desc "last [ref]", "Open a point"
    def last(*ref)
      files = filter(ref.first)
      case files.length
      when 0
        die "No file found for pattern '#{ref}'"
      else
        open_file(Conf.points_dir / files.last)
      end
    end

    desc "list [filter]", "List points"
    def list(*ref)
      filter(ref.first).each {|entry|
        puts entry.to_path
      }
    end

    desc "rm <ref>", "Remove a point"
    def rm(ref)
      files = filter(ref)
      case files.length
      when 0
        die "No file found for pattern '#{ref}'"
      when 1
        remove_file(Conf.points_dir / files.first)
      else
        die "Too many files found for pattern '#{ref}'"
      end
    end

  end

  class Client < Thor
    include Helpers

    no_commands {
      def filter(filter)
        Conf.clients_dir.entries.map {|client|
          if client.basename.to_path =~ /^(\.|_)/
          elsif !client.file?
          elsif filter && client.basename.to_path !~ glob(filter)
          else
            client
          end
        }.compact.sort
      end
    }

    desc "open <name>", "Open a client"
    def open(name)
      clients = filter(name)
      case clients.length
      when 0
        client = Conf.clients_dir + (name + Conf.file_suffix)
        create_and_open_file client, <<-CONTENT
# #{name}

        CONTENT
      when 1
        open_file clients.first
      else
        msg = ["Too many clients found for pattern '#{name}':"] +
              clients.map {|client| client.to_path }
        die msg.join("\n")
      end
    end

    # rename
    #   - rename dir
    #   - rename file
    #   - commit

    desc "list [ref]", "List clients"
    def list(*ref)
      filter(ref.first).each {|client|
        puts client.to_path
      }
    end

  end

  class Project < Thor
    include Helpers

    no_commands {
      def filter(filter)
        f = ->(entry, always) {
          entry.entries.map {|project|
            if project.basename.to_path =~ /^(\.|_)/
            else
              project = entry / project
              if project.file?
                if always or !filter || project.basename.to_path =~ glob(filter)
                  project
                end
              elsif project.directory?
                f.(project, always || !filter || project.basename.to_path =~ glob(filter))
              else
                die "File '#{project.relative_path_from($THEIR)}' is nor a file nor a directory"
              end
            end
          }.compact.sort
        }
        Conf.clients_dir.entries.map {|client|
          if client.basename.to_path =~ /^(\.|_)/
          elsif !client.directory?
          else
            f.(client, !filter || client.basename.to_path =~ glob(filter))
          end
        }.flatten.compact.sort
      end
    }

    desc "open <client name> <name>", "Open a project"
    def open(client_name, name)
      dir = Conf.clients_dir + client_name
      file = dir + (name + Conf.file_suffix)
      dir.mkpath
      open_or_create_file file, <<-CONTENT
# #{client_name} — #{name}

        CONTENT
    end

    desc "rm <client name> <name>", "Remove a project"
    def rm(client_name, name)
      dir = Conf.clients_dir + client_name
      file = dir + (name + Conf.file_suffix)
      file.unlink if file.file?
    end

    desc "list [ref]", "List projects"
    def list(*ref)
      filter(ref.first).each {|project|
        puts project.to_path
                    .gsub(/#{Conf.file_suffix_ptn}/, '')
                    .gsub(/\//, ' — ')
                    .gsub(/_/, ' ')
      }
    end

  end

  class Todo < Thor
    include Helpers

    desc "open", "Open todos"
    def open
      run_cmd "open #{$THEIR / ("_Todo" + Conf.file_suffix)}"
    end

  end

  class Main < Thor
    include Helpers

    desc "point SUBCOMMAND ...ARGS", "Manage points"
    subcommand "point", Point

    desc "client SUBCOMMAND ...ARGS", "Manage clients"
    subcommand "client", Client

    desc "project SUBCOMMAND ...ARGS", "Manage projects"
    subcommand "project", Project

    desc "todo SUBCOMMAND ...ARGS", "Manage todos"
    subcommand "todo", Todo

    Links = YAML.load_file($THEIR / "_Links.yml")
    desc "open SUBCOMMAND ...ARGS", "Open links"
    def open(*names)
      names.each{ |name|
        if link = Links[name]
          run_cmd "open #{link}"
        else
          warn "Can't find link '#{name}'"
        end
      }
    end

  end
end

Orga::Main.start(ARGV)
